// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_time = NULL;lv_obj_t *ui_centerimage = NULL;lv_obj_t *ui_staticsidesymbol = NULL;lv_obj_t *ui_pricepannel = NULL;lv_obj_t *ui_aoprice = NULL;lv_obj_t *ui_arprice = NULL;
// event funtions
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
}
}

void ui_event_pricepannel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_aoprice, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
      _ui_flag_modify( ui_arprice, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time, -21 );
lv_obj_set_y( ui_time, -202 );
lv_obj_set_align( ui_time, LV_ALIGN_CENTER );
lv_label_set_text(ui_time,"12:30PM");
lv_obj_set_style_text_font(ui_time, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_time, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_centerimage = lv_image_create(ui_Screen1);
lv_image_set_src(ui_centerimage, &ui_img_profile2_png);
lv_obj_set_width( ui_centerimage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_centerimage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_centerimage, 22 );
lv_obj_set_y( ui_centerimage, 6 );
lv_obj_set_align( ui_centerimage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_centerimage, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_centerimage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_transform_scale(ui_centerimage, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_staticsidesymbol = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_staticsidesymbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_staticsidesymbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_staticsidesymbol, 130 );
lv_obj_set_y( ui_staticsidesymbol, -12 );
lv_obj_set_align( ui_staticsidesymbol, LV_ALIGN_CENTER );
lv_label_set_text(ui_staticsidesymbol,">");
lv_obj_set_style_text_font(ui_staticsidesymbol, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_staticsidesymbol, 500, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pricepannel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_pricepannel, 172);
lv_obj_set_height( ui_pricepannel, 61);
lv_obj_set_x( ui_pricepannel, 3 );
lv_obj_set_y( ui_pricepannel, 203 );
lv_obj_set_align( ui_pricepannel, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_pricepannel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pricepannel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pricepannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_pricepannel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_pricepannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aoprice = lv_label_create(ui_pricepannel);
lv_obj_set_width( ui_aoprice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aoprice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_aoprice, 2 );
lv_obj_set_y( ui_aoprice, 0 );
lv_obj_set_align( ui_aoprice, LV_ALIGN_CENTER );
lv_label_set_text(ui_aoprice,"AO$14.09");
lv_obj_add_flag( ui_aoprice, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_font(ui_aoprice, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_aoprice, 250, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arprice = lv_label_create(ui_pricepannel);
lv_obj_set_width( ui_arprice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_arprice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_arprice, 2 );
lv_obj_set_y( ui_arprice, 0 );
lv_obj_set_align( ui_arprice, LV_ALIGN_CENTER );
lv_label_set_text(ui_arprice,"AR$15.09");
lv_obj_set_style_text_font(ui_arprice, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_arprice, 250, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_pricepannel, ui_event_pricepannel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_time= NULL;
ui_centerimage= NULL;
ui_staticsidesymbol= NULL;
ui_pricepannel= NULL;
ui_aoprice= NULL;
ui_arprice= NULL;

}
