// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_time;
extern lv_obj_t *ui_centerimage;
extern lv_obj_t *ui_staticsidesymbol;
extern void ui_event_pricepannel( lv_event_t * e);
extern lv_obj_t *ui_pricepannel;
extern lv_obj_t *ui_aoprice;
extern lv_obj_t *ui_arprice;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

