// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: hardware_wallet_01

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/** Optional callback when Screen 2 is created (for app to add QR scanner UI). Set from main. */
extern void (*app_screen2_init_cb)(lv_obj_t *screen2);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
