// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Keyboard1 = NULL;lv_obj_t *ui_TextArea1 = NULL;
// event funtions
void ui_event_TextArea1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x88BF6C), (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
lv_obj_set_style_bg_opa(ui_Screen1, 255, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));

lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x88BF6C), (lv_style_selector_t)(LV_PART_SCROLLBAR | LV_STATE_DEFAULT));
lv_obj_set_style_bg_opa(ui_Screen1, 255, (lv_style_selector_t)(LV_PART_SCROLLBAR | LV_STATE_DEFAULT));

ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
lv_obj_set_width( ui_Keyboard1, 316);
lv_obj_set_height( ui_Keyboard1, 166);
lv_obj_set_x( ui_Keyboard1, 1 );
lv_obj_set_y( ui_Keyboard1, 153 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_TextArea1 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea1, 150);
lv_obj_set_height( ui_TextArea1, 70);
lv_obj_set_x( ui_TextArea1, -18 );
lv_obj_set_y( ui_TextArea1, -42 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");

lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Keyboard1= NULL;
ui_TextArea1= NULL;

}
