// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t *e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_time;
extern lv_obj_t *ui_Image1;
extern void ui_event_Panel1(lv_event_t *e);
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_aoprice;
extern lv_obj_t *ui_arprice;
extern lv_obj_t *ui_personname;
extern lv_obj_t *ui_arrow;
extern lv_obj_t *ui_whichscreenmark;
extern lv_obj_t *ui_wifi_not_enable;
extern lv_obj_t *ui_wifi_enable;

/** Update wifi icon on home screen. Call with 1 when connected, 0 when disconnected. */
void ui_Screen1_set_wifi_connected(int connected);

/** Update AO and AR price labels (e.g. "AO$0.15", "AR$23.50"). NULL = leave unchanged. */
void ui_Screen1_set_prices(const char *ao_price, const char *ar_price);

#ifdef __cplusplus
}
#endif

#endif
