// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t *e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_whichscreenmark2;
extern void ui_event_settingbutton(lv_event_t *e);
extern lv_obj_t *ui_settingbutton;
extern lv_obj_t *ui_arrow2;
extern lv_obj_t *ui_arrow3;
extern lv_obj_t *ui_ImgButton2;
extern lv_obj_t *ui_bottom_image_for_page;
extern lv_obj_t *ui_time2;
extern lv_obj_t *ui_wifi_not_enable2;
extern lv_obj_t *ui_wifi_enable2;

void ui_Screen2_set_wifi_connected(int connected);

#ifdef __cplusplus
}
#endif

#endif
