// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3
// Theme off; panel + profile image from wallet3.

#include "../ui.h"
#include <time.h>
#include <stdio.h>
#include <string.h>

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_time = NULL;
lv_obj_t *ui_Image1 = NULL;
lv_obj_t *ui_Panel1 = NULL;
lv_obj_t *ui_aoprice = NULL;
lv_obj_t *ui_arprice = NULL;
lv_obj_t *ui_personname = NULL;
lv_obj_t *ui_arrow = NULL;
lv_obj_t *ui_whichscreenmark = NULL;
lv_obj_t *ui_wifi_not_enable = NULL;
lv_obj_t *ui_wifi_enable = NULL;

static lv_timer_t *s_time_timer = NULL;

#define UI_PRICE_BUF_SIZE 24
static char s_ao_price_buf[UI_PRICE_BUF_SIZE] = "";
static char s_ar_price_buf[UI_PRICE_BUF_SIZE] = "";

void ui_Screen1_set_wifi_connected(int connected)
{
	if (ui_wifi_not_enable && ui_wifi_enable) {
		if (connected) {
			lv_obj_add_flag(ui_wifi_not_enable, LV_OBJ_FLAG_HIDDEN);
			lv_obj_remove_flag(ui_wifi_enable, LV_OBJ_FLAG_HIDDEN);
		} else {
			lv_obj_remove_flag(ui_wifi_not_enable, LV_OBJ_FLAG_HIDDEN);
			lv_obj_add_flag(ui_wifi_enable, LV_OBJ_FLAG_HIDDEN);
		}
	}
}

void ui_Screen1_set_prices(const char *ao_price, const char *ar_price)
{
	if (ao_price && ui_aoprice) {
		lv_label_set_text(ui_aoprice, ao_price);
		strncpy(s_ao_price_buf, ao_price, UI_PRICE_BUF_SIZE - 1);
		s_ao_price_buf[UI_PRICE_BUF_SIZE - 1] = '\0';
	}
	if (ar_price && ui_arprice) {
		lv_label_set_text(ui_arprice, ar_price);
		strncpy(s_ar_price_buf, ar_price, UI_PRICE_BUF_SIZE - 1);
		s_ar_price_buf[UI_PRICE_BUF_SIZE - 1] = '\0';
	}
}

#define UI_TIME_BUF_SIZE 32

static void ui_time_timer_cb(lv_timer_t *timer)
{
	time_t now = time(NULL);
	struct tm *tm = localtime(&now);
	if (tm == NULL) return;
	int h = tm->tm_hour;
	int m = tm->tm_min;
	int pm = (h >= 12);
	if (h == 0) h = 12;
	else if (h > 12) h -= 12;
	char buf[UI_TIME_BUF_SIZE];
	snprintf(buf, sizeof(buf), "%d:%02d%s", h, m, pm ? "PM" : "AM");
	if (ui_time) lv_label_set_text(ui_time, buf);
	if (ui_time2) lv_label_set_text(ui_time2, buf);
	if (ui_time3) lv_label_set_text(ui_time3, buf);
	if (ui_time6) lv_label_set_text(ui_time6, buf);
	if (ui_time8) lv_label_set_text(ui_time8, buf);
	if (ui_time1) lv_label_set_text(ui_time1, buf);
	if (ui_time5) lv_label_set_text(ui_time5, buf);
	if (ui_time5_pwd) lv_label_set_text(ui_time5_pwd, buf);
}

void ui_event_Screen1(lv_event_t *e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
		lv_indev_wait_release(lv_indev_active());
		_ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Screen2_screen_init);
	}
}

void ui_event_Panel1(lv_event_t *e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_CLICKED) {
		_ui_flag_modify(ui_aoprice, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
		_ui_flag_modify(ui_arprice, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
		/* Ensure the now-visible label shows the correct token price */
		if (ui_aoprice && !lv_obj_has_flag(ui_aoprice, LV_OBJ_FLAG_HIDDEN) && s_ao_price_buf[0])
			lv_label_set_text(ui_aoprice, s_ao_price_buf);
		if (ui_arprice && !lv_obj_has_flag(ui_arprice, LV_OBJ_FLAG_HIDDEN) && s_ar_price_buf[0])
			lv_label_set_text(ui_arprice, s_ar_price_buf);
	}
}

void ui_Screen1_screen_init(void)
{
	ui_Screen1 = lv_obj_create(NULL);
	lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);
	lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x88BF6C), (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_bg_opa(ui_Screen1, LV_OPA_COVER, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));

	ui_time = lv_label_create(ui_Screen1);
	lv_obj_set_width(ui_time, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_time, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_time, -21);
	lv_obj_set_y(ui_time, -213);
	lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
	lv_label_set_text(ui_time, "12:30PM");
	lv_obj_set_style_text_font(ui_time, &ui_font_Pixel, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_transform_scale(ui_time, 350, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));

	ui_Image1 = lv_image_create(ui_Screen1);
	lv_image_set_src(ui_Image1, &ui_img_profile2_png);
	lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_Image1, 0);
	lv_obj_set_y(ui_Image1, -31);
	lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
	lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);
	lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);
	lv_image_set_scale(ui_Image1, 200);

	ui_Panel1 = lv_obj_create(ui_Screen1);
	lv_obj_set_width(ui_Panel1, 100);
	lv_obj_set_height(ui_Panel1, 50);
	lv_obj_set_x(ui_Panel1, 8);
	lv_obj_set_y(ui_Panel1, 207);
	lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
	lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);

	ui_aoprice = lv_label_create(ui_Panel1);
	lv_obj_set_width(ui_aoprice, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_aoprice, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_aoprice, -1);
	lv_obj_set_y(ui_aoprice, 1);
	lv_obj_set_align(ui_aoprice, LV_ALIGN_CENTER);
	lv_label_set_text(ui_aoprice, "AO$4.08");
	lv_obj_add_flag(ui_aoprice, LV_OBJ_FLAG_HIDDEN);

	ui_arprice = lv_label_create(ui_Panel1);
	lv_obj_set_width(ui_arprice, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_arprice, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_arprice, 2);
	lv_obj_set_y(ui_arprice, 1);
	lv_obj_set_align(ui_arprice, LV_ALIGN_CENTER);
	lv_label_set_text(ui_arprice, "AR$2.52");

	ui_personname = lv_label_create(ui_Screen1);
	lv_obj_set_width(ui_personname, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_personname, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_personname, 7);
	lv_obj_set_y(ui_personname, 92);
	lv_obj_set_align(ui_personname, LV_ALIGN_CENTER);
	lv_label_set_text(ui_personname, "Hope's\nVault");
	lv_obj_set_style_text_align(ui_personname, LV_TEXT_ALIGN_CENTER, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_text_font(ui_personname, &ui_font_Pixel, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));

	ui_arrow = lv_label_create(ui_Screen1);
	lv_obj_set_width(ui_arrow, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_arrow, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_arrow, 133);
	lv_obj_set_y(ui_arrow, -23);
	lv_obj_set_align(ui_arrow, LV_ALIGN_CENTER);
	lv_label_set_text(ui_arrow, ">");
	lv_obj_set_style_text_align(ui_arrow, LV_TEXT_ALIGN_CENTER, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_text_font(ui_arrow, &ui_font_Pixel, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_transform_scale(ui_arrow, 450, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));

	ui_whichscreenmark = lv_label_create(ui_Screen1);
	lv_obj_set_width(ui_whichscreenmark, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_whichscreenmark, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_whichscreenmark, -19);
	lv_obj_set_y(ui_whichscreenmark, 136);
	lv_obj_set_align(ui_whichscreenmark, LV_ALIGN_CENTER);
	lv_label_set_text(ui_whichscreenmark, "_ . .");
	lv_obj_set_style_text_align(ui_whichscreenmark, LV_TEXT_ALIGN_CENTER, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_text_font(ui_whichscreenmark, &ui_font_Pixel, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_transform_scale(ui_whichscreenmark, 450, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));

	ui_wifi_not_enable = lv_image_create(ui_Screen1);
	lv_image_set_src(ui_wifi_not_enable, &ui_img_wifi_not_enable_png);
	lv_obj_set_width(ui_wifi_not_enable, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_wifi_not_enable, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_wifi_not_enable, 113);
	lv_obj_set_y(ui_wifi_not_enable, -213);
	lv_obj_set_align(ui_wifi_not_enable, LV_ALIGN_CENTER);
	lv_obj_add_flag(ui_wifi_not_enable, LV_OBJ_FLAG_CLICKABLE);
	lv_obj_remove_flag(ui_wifi_not_enable, LV_OBJ_FLAG_SCROLLABLE);
	lv_image_set_scale(ui_wifi_not_enable, 100);

	ui_wifi_enable = lv_image_create(ui_Screen1);
	lv_image_set_src(ui_wifi_enable, &ui_img_wifi_enable_png);
	lv_obj_set_width(ui_wifi_enable, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_wifi_enable, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_wifi_enable, 113);
	lv_obj_set_y(ui_wifi_enable, -213);
	lv_obj_set_align(ui_wifi_enable, LV_ALIGN_CENTER);
	lv_obj_add_flag(ui_wifi_enable, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);
	lv_obj_remove_flag(ui_wifi_enable, LV_OBJ_FLAG_SCROLLABLE);
	lv_image_set_scale(ui_wifi_enable, 100);

	lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
	lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

	/* Real-time clock in IST (Indian Standard Time); update every second */
	if (s_time_timer == NULL) {
		ui_time_timer_cb(NULL);  /* set initial text */
		s_time_timer = lv_timer_create(ui_time_timer_cb, 1000, NULL);
	}
}

void ui_Screen1_screen_destroy(void)
{
	if (s_time_timer) {
		lv_timer_del(s_time_timer);
		s_time_timer = NULL;
	}
	if (ui_Screen1)
		lv_obj_del(ui_Screen1);
	ui_Screen1 = NULL;
	ui_time = NULL;
	ui_Image1 = NULL;
	ui_Panel1 = NULL;
	ui_aoprice = NULL;
	ui_arprice = NULL;
	ui_personname = NULL;
	ui_arrow = NULL;
	ui_whichscreenmark = NULL;
	ui_wifi_not_enable = NULL;
	ui_wifi_enable = NULL;
}
