// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "../ui.h"
#include "ui_new_note_for_word_count.h"

lv_obj_t *ui_Screen3 = NULL;
lv_obj_t *ui_time3 = NULL;
lv_obj_t *ui_wifi_not_enable3 = NULL;
lv_obj_t *ui_wifi_enable3 = NULL;
lv_obj_t *ui_whichscreenmark3 = NULL;
lv_obj_t *ui_bottom_image_for_page2 = NULL;
lv_obj_t *ui_ImgButton3 = NULL;
lv_obj_t *ui_arrow4 = NULL;

void ui_Screen3_set_wifi_connected(int connected)
{
	if (ui_wifi_not_enable3 && ui_wifi_enable3) {
		if (connected) {
			lv_obj_add_flag(ui_wifi_not_enable3, LV_OBJ_FLAG_HIDDEN);
			lv_obj_remove_flag(ui_wifi_enable3, LV_OBJ_FLAG_HIDDEN);
		} else {
			lv_obj_remove_flag(ui_wifi_not_enable3, LV_OBJ_FLAG_HIDDEN);
			lv_obj_add_flag(ui_wifi_enable3, LV_OBJ_FLAG_HIDDEN);
		}
	}
}

void ui_event_Screen3(lv_event_t *e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
		lv_indev_wait_release(lv_indev_active());
		_ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Screen2_screen_init);
	}
}

static void verification_btn_cb(lv_event_t *e)
{
	lv_event_code_t code = lv_event_get_code(e);
	if (code == LV_EVENT_CLICKED && ui_new_note_for_word_count)
		_ui_screen_change(&ui_new_note_for_word_count, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_new_note_for_word_count_screen_init);
}

void ui_Screen3_screen_init(void)
{
	ui_Screen3 = lv_obj_create(NULL);
	lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);
	lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x88BF6C), (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_bg_opa(ui_Screen3, LV_OPA_COVER, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));

	ui_time3 = lv_label_create(ui_Screen3);
	lv_obj_set_width(ui_time3, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_time3, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_time3, -56);
	lv_obj_set_y(ui_time3, -216);
	lv_obj_set_align(ui_time3, LV_ALIGN_CENTER);
	lv_label_set_text(ui_time3, "12:30PM");
	lv_obj_set_style_text_font(ui_time3, &ui_font_Pixel, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_transform_scale(ui_time3, 350, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));

	ui_wifi_not_enable3 = lv_image_create(ui_Screen3);
	lv_image_set_src(ui_wifi_not_enable3, &ui_img_wifi_not_enable_png);
	lv_obj_set_width(ui_wifi_not_enable3, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_wifi_not_enable3, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_wifi_not_enable3, 113);
	lv_obj_set_y(ui_wifi_not_enable3, -213);
	lv_obj_set_align(ui_wifi_not_enable3, LV_ALIGN_CENTER);
	lv_obj_add_flag(ui_wifi_not_enable3, LV_OBJ_FLAG_CLICKABLE);
	lv_obj_remove_flag(ui_wifi_not_enable3, LV_OBJ_FLAG_SCROLLABLE);
	lv_image_set_scale(ui_wifi_not_enable3, 100);

	ui_wifi_enable3 = lv_image_create(ui_Screen3);
	lv_image_set_src(ui_wifi_enable3, &ui_img_wifi_enable_png);
	lv_obj_set_width(ui_wifi_enable3, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_wifi_enable3, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_wifi_enable3, 113);
	lv_obj_set_y(ui_wifi_enable3, -213);
	lv_obj_set_align(ui_wifi_enable3, LV_ALIGN_CENTER);
	lv_obj_add_flag(ui_wifi_enable3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);
	lv_obj_remove_flag(ui_wifi_enable3, LV_OBJ_FLAG_SCROLLABLE);
	lv_image_set_scale(ui_wifi_enable3, 100);

	ui_whichscreenmark3 = lv_label_create(ui_Screen3);
	lv_obj_set_width(ui_whichscreenmark3, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_whichscreenmark3, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_whichscreenmark3, -19);
	lv_obj_set_y(ui_whichscreenmark3, 136);
	lv_obj_set_align(ui_whichscreenmark3, LV_ALIGN_CENTER);
	lv_label_set_text(ui_whichscreenmark3, ". . _");
	lv_obj_set_style_text_align(ui_whichscreenmark3, LV_TEXT_ALIGN_CENTER, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_text_font(ui_whichscreenmark3, &ui_font_Pixel, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_transform_scale(ui_whichscreenmark3, 450, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));

	ui_bottom_image_for_page2 = lv_image_create(ui_Screen3);
	lv_image_set_src(ui_bottom_image_for_page2, &ui_img_under_image_png);
	lv_obj_set_width(ui_bottom_image_for_page2, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_bottom_image_for_page2, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_bottom_image_for_page2, -106);
	lv_obj_set_y(ui_bottom_image_for_page2, 160);
	lv_obj_set_align(ui_bottom_image_for_page2, LV_ALIGN_CENTER);
	lv_obj_add_flag(ui_bottom_image_for_page2, LV_OBJ_FLAG_CLICKABLE);
	lv_obj_remove_flag(ui_bottom_image_for_page2, LV_OBJ_FLAG_SCROLLABLE);

	ui_ImgButton3 = lv_imagebutton_create(ui_Screen3);
	lv_imagebutton_set_src(ui_ImgButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_verification_png, NULL);
	lv_obj_set_width(ui_ImgButton3, 240);
	lv_obj_set_height(ui_ImgButton3, 122);
	lv_obj_set_x(ui_ImgButton3, 1);
	lv_obj_set_y(ui_ImgButton3, -9);
	lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);
	lv_obj_add_event_cb(ui_ImgButton3, verification_btn_cb, LV_EVENT_CLICKED, NULL);

	ui_arrow4 = lv_label_create(ui_Screen3);
	lv_obj_set_width(ui_arrow4, LV_SIZE_CONTENT);
	lv_obj_set_height(ui_arrow4, LV_SIZE_CONTENT);
	lv_obj_set_x(ui_arrow4, -141);
	lv_obj_set_y(ui_arrow4, -18);
	lv_obj_set_align(ui_arrow4, LV_ALIGN_CENTER);
	lv_label_set_text(ui_arrow4, "<");
	lv_obj_set_style_text_align(ui_arrow4, LV_TEXT_ALIGN_CENTER, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_text_font(ui_arrow4, &ui_font_Pixel, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));
	lv_obj_set_style_transform_scale(ui_arrow4, 450, (lv_style_selector_t)(LV_PART_MAIN | LV_STATE_DEFAULT));

	lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);
}

void ui_Screen3_screen_destroy(void)
{
	if (ui_Screen3)
		lv_obj_del(ui_Screen3);
	ui_Screen3 = NULL;
	ui_time3 = NULL;
	ui_wifi_not_enable3 = NULL;
	ui_wifi_enable3 = NULL;
	ui_whichscreenmark3 = NULL;
	ui_bottom_image_for_page2 = NULL;
	ui_ImgButton3 = NULL;
	ui_arrow4 = NULL;
}
