// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: hardware_wallet_01

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_clock = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_persons_name = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Label5 = NULL;
// event funtions
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clock = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_clock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock, -1 );
lv_obj_set_y( ui_clock, -210 );
lv_obj_set_align( ui_clock, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock,"12:30PM");
lv_obj_set_style_text_font(ui_clock, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_clock, 250, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_profile2_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, -5 );
lv_obj_set_y( ui_Image2, -25 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2, (180 * 256) / 100);

ui_persons_name = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_persons_name, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_persons_name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_persons_name, 20 );
lv_obj_set_y( ui_persons_name, 89 );
lv_obj_set_align( ui_persons_name, LV_ALIGN_CENTER );
lv_label_set_text(ui_persons_name,"Hope's \nVault");
lv_obj_set_style_text_align(ui_persons_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_persons_name, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_persons_name, 180, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 127 );
lv_obj_set_y( ui_Label3, -21 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,">");
lv_obj_set_style_text_font(ui_Label3, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_Label3, 400, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 173);
lv_obj_set_height( ui_Panel3, 50);
lv_obj_set_x( ui_Panel3, 23 );
lv_obj_set_y( ui_Panel3, 209 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_Panel3, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -7 );
lv_obj_set_y( ui_Label5, 2 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"AO $15.09");
lv_obj_set_style_text_font(ui_Label5, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_clock= NULL;
ui_Image2= NULL;
ui_persons_name= NULL;
ui_Label3= NULL;
ui_Panel3= NULL;
ui_Label5= NULL;

}
