// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: hardware_wallet_01

#include "../ui.h"
#include "../ui_events.h"

lv_obj_t *ui_Screen2 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

if (app_screen2_init_cb != NULL) {
    app_screen2_init_cb(ui_Screen2);
}
}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;

}
