// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef _WALLET3_UI_H
#define _WALLET3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_setting_screen.h"
#include "ui_Screen3.h"
#include "ui_wallet_generation_waiting_screen.h"
#include "ui_words_screen.h"
#include "ui_last_words_screen.h"
#include "ui_note_for_password_creation.h"
#include "ui_wifi_password_screen.h"
#include "ui_note_for_word_count.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_profile2_png);   // assets/profile2.png
LV_IMG_DECLARE( ui_img_wifi_not_enable_png);   // assets/wifi_not_enable.png
LV_IMG_DECLARE( ui_img_wifi_enable_png);   // assets/wifi_enable.png
LV_IMG_DECLARE( ui_img_settingsicon_png);   // assets/settingsicon.png
LV_IMG_DECLARE( ui_img_wallet_png);   // assets/wallet.png
LV_IMG_DECLARE( ui_img_under_image_png);   // assets/under_image.png
LV_IMG_DECLARE( ui_img_verification_png);   // assets/verification.png
LV_IMG_DECLARE( ui_img_wallet_watiting_png);   // assets/wallet_watiting.png
LV_IMG_DECLARE( ui_img_backbutton_png);   // assets/backbutton.png
LV_IMG_DECLARE( ui_img_nextbutton_png);   // assets/nextbutton.png
LV_IMG_DECLARE( ui_img_finishbutton_png);   // assets/finishbutton.png
LV_IMG_DECLARE( ui_img_letsgobutton_png);   // assets/letsgobutton.png

// FONTS
LV_FONT_DECLARE( ui_font_Pixel);
LV_FONT_DECLARE( ui_font_pixel_heading);
LV_FONT_DECLARE( ui_font_pixel_wordings);
LV_FONT_DECLARE( ui_font_pixel_wordings_small);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
