// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_last_words_screen = NULL;lv_obj_t *ui_time1 = NULL;lv_obj_t *ui_wifi_not_enable1 = NULL;lv_obj_t *ui_wifi_enable1 = NULL;lv_obj_t *ui_number_count_for_words1 = NULL;lv_obj_t *ui_words1 = NULL;lv_obj_t *ui_ImgButton1 = NULL;lv_obj_t *ui_ImgButton4 = NULL;
// event funtions

// build funtions

void ui_last_words_screen_screen_init(void)
{
ui_last_words_screen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_last_words_screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_last_words_screen, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_last_words_screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time1 = lv_label_create(ui_last_words_screen);
lv_obj_set_width( ui_time1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time1, -34 );
lv_obj_set_y( ui_time1, -216 );
lv_obj_set_align( ui_time1, LV_ALIGN_CENTER );
lv_label_set_text(ui_time1,"12:30PM");
lv_obj_set_style_text_font(ui_time1, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_time1, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_not_enable1 = lv_image_create(ui_last_words_screen);
lv_image_set_src(ui_wifi_not_enable1, &ui_img_wifi_not_enable_png);
lv_obj_set_width( ui_wifi_not_enable1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_not_enable1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_not_enable1, 113 );
lv_obj_set_y( ui_wifi_not_enable1, -213 );
lv_obj_set_align( ui_wifi_not_enable1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_not_enable1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_not_enable1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_not_enable1,100);

ui_wifi_enable1 = lv_image_create(ui_last_words_screen);
lv_image_set_src(ui_wifi_enable1, &ui_img_wifi_enable_png);
lv_obj_set_width( ui_wifi_enable1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_enable1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_enable1, 113 );
lv_obj_set_y( ui_wifi_enable1, -213 );
lv_obj_set_align( ui_wifi_enable1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_enable1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_enable1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_enable1,100);

ui_number_count_for_words1 = lv_label_create(ui_last_words_screen);
lv_obj_set_width( ui_number_count_for_words1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_number_count_for_words1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_number_count_for_words1, -16 );
lv_obj_set_y( ui_number_count_for_words1, -85 );
lv_obj_set_align( ui_number_count_for_words1, LV_ALIGN_CENTER );
lv_label_set_text(ui_number_count_for_words1,"12/12");
lv_obj_set_style_text_font(ui_number_count_for_words1, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_number_count_for_words1, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_words1 = lv_label_create(ui_last_words_screen);
lv_obj_set_width( ui_words1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_words1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_words1, -26 );
lv_obj_set_y( ui_words1, -39 );
lv_obj_set_align( ui_words1, LV_ALIGN_CENTER );
lv_label_set_text(ui_words1,"doctor");
lv_obj_set_style_text_decor(ui_words1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_words1, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_words1, 400, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton1 = lv_imagebutton_create(ui_last_words_screen);
lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backbutton_png, NULL);
lv_obj_set_width( ui_ImgButton1, 145);
lv_obj_set_height( ui_ImgButton1, 73);
lv_obj_set_x( ui_ImgButton1, -77 );
lv_obj_set_y( ui_ImgButton1, 84 );
lv_obj_set_align( ui_ImgButton1, LV_ALIGN_CENTER );

ui_ImgButton4 = lv_imagebutton_create(ui_last_words_screen);
lv_imagebutton_set_src(ui_ImgButton4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_finishbutton_png, NULL);
lv_obj_set_width( ui_ImgButton4, 143);
lv_obj_set_height( ui_ImgButton4, 71);
lv_obj_set_x( ui_ImgButton4, 81 );
lv_obj_set_y( ui_ImgButton4, 81 );
lv_obj_set_align( ui_ImgButton4, LV_ALIGN_CENTER );

}

void ui_last_words_screen_screen_destroy(void)
{
   if (ui_last_words_screen) lv_obj_del(ui_last_words_screen);

// NULL screen variables
ui_last_words_screen= NULL;
ui_time1= NULL;
ui_wifi_not_enable1= NULL;
ui_wifi_enable1= NULL;
ui_number_count_for_words1= NULL;
ui_words1= NULL;
ui_ImgButton1= NULL;
ui_ImgButton4= NULL;

}
