// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef UI_LAST_WORDS_SCREEN_H
#define UI_LAST_WORDS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_last_words_screen
extern void ui_last_words_screen_screen_init(void);
extern void ui_last_words_screen_screen_destroy(void);
extern lv_obj_t *ui_last_words_screen;
extern lv_obj_t *ui_time1;
extern lv_obj_t *ui_wifi_not_enable1;
extern lv_obj_t *ui_wifi_enable1;
extern lv_obj_t *ui_number_count_for_words1;
extern lv_obj_t *ui_words1;
extern lv_obj_t *ui_ImgButton1;
extern lv_obj_t *ui_ImgButton4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

