// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_note_for_password = NULL;lv_obj_t *ui_time5 = NULL;lv_obj_t *ui_wifi_enable5 = NULL;lv_obj_t *ui_wifi_not_enable5 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_note_ = NULL;lv_obj_t *ui_ImgButton1 = NULL;
// event funtions

// build funtions

void ui_note_for_password_screen_init(void)
{
ui_note_for_password = lv_obj_create(NULL);
lv_obj_remove_flag( ui_note_for_password, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_note_for_password, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_note_for_password, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time5 = lv_label_create(ui_note_for_password);
lv_obj_set_width( ui_time5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time5, -34 );
lv_obj_set_y( ui_time5, -216 );
lv_obj_set_align( ui_time5, LV_ALIGN_CENTER );
lv_label_set_text(ui_time5,"12:30PM");
lv_obj_set_style_text_font(ui_time5, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_time5, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_enable5 = lv_image_create(ui_note_for_password);
lv_image_set_src(ui_wifi_enable5, &ui_img_wifi_enable_png);
lv_obj_set_width( ui_wifi_enable5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_enable5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_enable5, 113 );
lv_obj_set_y( ui_wifi_enable5, -213 );
lv_obj_set_align( ui_wifi_enable5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_enable5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_enable5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_enable5,100);

ui_wifi_not_enable5 = lv_image_create(ui_note_for_password);
lv_image_set_src(ui_wifi_not_enable5, &ui_img_wifi_not_enable_png);
lv_obj_set_width( ui_wifi_not_enable5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_not_enable5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_not_enable5, 113 );
lv_obj_set_y( ui_wifi_not_enable5, -213 );
lv_obj_set_align( ui_wifi_not_enable5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_not_enable5, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_not_enable5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_not_enable5,100);

ui_Label2 = lv_label_create(ui_note_for_password);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -3 );
lv_obj_set_y( ui_Label2, -140 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Note");
lv_obj_set_style_text_decor(ui_Label2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_pixel_heading, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_note_ = lv_label_create(ui_note_for_password);
lv_obj_set_width( ui_note_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_note_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_note_, 2 );
lv_obj_set_y( ui_note_, -2 );
lv_obj_set_align( ui_note_, LV_ALIGN_CENTER );
lv_label_set_text(ui_note_,"> On the next screen\n\nyou would be ask to\n\ncreate a password.\n\nkindly write down, or\n\nremember this password,\n\nas it is the main\n\ndecryption key for \n\nsigning tx. ");
lv_obj_set_style_text_align(ui_note_, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_note_, &ui_font_pixel_wordings_small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton1 = lv_imagebutton_create(ui_note_for_password);
lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_letsgobutton_png, NULL);
lv_obj_set_width( ui_ImgButton1, 105);
lv_obj_set_height( ui_ImgButton1, 54);
lv_obj_set_x( ui_ImgButton1, -1 );
lv_obj_set_y( ui_ImgButton1, 146 );
lv_obj_set_align( ui_ImgButton1, LV_ALIGN_CENTER );

}

void ui_note_for_password_screen_destroy(void)
{
   if (ui_note_for_password) lv_obj_del(ui_note_for_password);

// NULL screen variables
ui_note_for_password= NULL;
ui_time5= NULL;
ui_wifi_enable5= NULL;
ui_wifi_not_enable5= NULL;
ui_Label2= NULL;
ui_note_= NULL;
ui_ImgButton1= NULL;

}
