// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef UI_NOTE_FOR_PASSWORD_CREATION_H
#define UI_NOTE_FOR_PASSWORD_CREATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_note_for_password_creation
extern void ui_note_for_password_creation_screen_init(void);
extern void ui_note_for_password_creation_screen_destroy(void);
extern lv_obj_t *ui_note_for_password_creation;
extern lv_obj_t *ui_time7;
extern lv_obj_t *ui_wifi_enable7;
extern lv_obj_t *ui_wifi_not_enable7;
extern lv_obj_t *ui_Note1;
extern lv_obj_t *ui_note_text1;
extern lv_obj_t *ui_lets_go_button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

