// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_new_note_for_word_count = NULL;lv_obj_t *ui_time8 = NULL;lv_obj_t *ui_wifi_enable8 = NULL;lv_obj_t *ui_wifi_not_enable8 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_ImgButton8 = NULL;
// event funtions

// build funtions

void ui_new_note_for_word_count_screen_init(void)
{
ui_new_note_for_word_count = lv_obj_create(NULL);
lv_obj_remove_flag( ui_new_note_for_word_count, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_new_note_for_word_count, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_new_note_for_word_count, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time8 = lv_label_create(ui_new_note_for_word_count);
lv_obj_set_width( ui_time8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time8, -34 );
lv_obj_set_y( ui_time8, -216 );
lv_obj_set_align( ui_time8, LV_ALIGN_CENTER );
lv_label_set_text(ui_time8,"12:30PM");
lv_obj_set_style_text_font(ui_time8, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_time8, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_enable8 = lv_image_create(ui_new_note_for_word_count);
lv_image_set_src(ui_wifi_enable8, &ui_img_wifi_enable_png);
lv_obj_set_width( ui_wifi_enable8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_enable8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_enable8, 113 );
lv_obj_set_y( ui_wifi_enable8, -213 );
lv_obj_set_align( ui_wifi_enable8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_enable8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_enable8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_enable8,100);

ui_wifi_not_enable8 = lv_image_create(ui_new_note_for_word_count);
lv_image_set_src(ui_wifi_not_enable8, &ui_img_wifi_not_enable_png);
lv_obj_set_width( ui_wifi_not_enable8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_not_enable8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_not_enable8, 113 );
lv_obj_set_y( ui_wifi_not_enable8, -213 );
lv_obj_set_align( ui_wifi_not_enable8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_not_enable8, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_not_enable8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_not_enable8,100);

ui_Label10 = lv_label_create(ui_new_note_for_word_count);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -3 );
lv_obj_set_y( ui_Label10, -140 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Note");
lv_obj_set_style_text_decor(ui_Label10, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label10, &ui_font_pixel_heading, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_new_note_for_word_count);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, 2 );
lv_obj_set_y( ui_Label11, -2 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"> On the next screen you \n\nwill be displayed 12\n\nunique characters.\n\n\n> Make sure to write them\n\ndown somewhere safe.\n\n\n> If you loose them there \n\nis no way to recover your\n\nwallet ");
lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &ui_font_pixel_wordings_small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton8 = lv_imagebutton_create(ui_new_note_for_word_count);
lv_imagebutton_set_src(ui_ImgButton8, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_letsgobutton_png, NULL);
lv_obj_set_width( ui_ImgButton8, 105);
lv_obj_set_height( ui_ImgButton8, 54);
lv_obj_set_x( ui_ImgButton8, -1 );
lv_obj_set_y( ui_ImgButton8, 146 );
lv_obj_set_align( ui_ImgButton8, LV_ALIGN_CENTER );

}

void ui_new_note_for_word_count_screen_destroy(void)
{
   if (ui_new_note_for_word_count) lv_obj_del(ui_new_note_for_word_count);

// NULL screen variables
ui_new_note_for_word_count= NULL;
ui_time8= NULL;
ui_wifi_enable8= NULL;
ui_wifi_not_enable8= NULL;
ui_Label10= NULL;
ui_Label11= NULL;
ui_ImgButton8= NULL;

}
