// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_note_for_password_creation = NULL;lv_obj_t *ui_time7 = NULL;lv_obj_t *ui_wifi_enable7 = NULL;lv_obj_t *ui_wifi_not_enable7 = NULL;lv_obj_t *ui_Note1 = NULL;lv_obj_t *ui_note_text1 = NULL;lv_obj_t *ui_lets_go_button1 = NULL;
// event funtions

// build funtions

void ui_note_for_password_creation_screen_init(void)
{
ui_note_for_password_creation = lv_obj_create(NULL);
lv_obj_remove_flag( ui_note_for_password_creation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_note_for_password_creation, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_note_for_password_creation, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time7 = lv_label_create(ui_note_for_password_creation);
lv_obj_set_width( ui_time7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time7, -34 );
lv_obj_set_y( ui_time7, -216 );
lv_obj_set_align( ui_time7, LV_ALIGN_CENTER );
lv_label_set_text(ui_time7,"12:30PM");
lv_obj_set_style_text_font(ui_time7, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_time7, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_enable7 = lv_image_create(ui_note_for_password_creation);
lv_image_set_src(ui_wifi_enable7, &ui_img_wifi_enable_png);
lv_obj_set_width( ui_wifi_enable7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_enable7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_enable7, 113 );
lv_obj_set_y( ui_wifi_enable7, -213 );
lv_obj_set_align( ui_wifi_enable7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_enable7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_enable7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_enable7,100);

ui_wifi_not_enable7 = lv_image_create(ui_note_for_password_creation);
lv_image_set_src(ui_wifi_not_enable7, &ui_img_wifi_not_enable_png);
lv_obj_set_width( ui_wifi_not_enable7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_not_enable7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_not_enable7, 113 );
lv_obj_set_y( ui_wifi_not_enable7, -213 );
lv_obj_set_align( ui_wifi_not_enable7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_not_enable7, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_not_enable7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_not_enable7,100);

ui_Note1 = lv_label_create(ui_note_for_password_creation);
lv_obj_set_width( ui_Note1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Note1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Note1, -42 );
lv_obj_set_y( ui_Note1, -146 );
lv_obj_set_align( ui_Note1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Note1,"Note");
lv_obj_set_style_text_decor(ui_Note1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Note1, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_Note1, 600, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_note_text1 = lv_label_create(ui_note_for_password_creation);
lv_obj_set_width( ui_note_text1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_note_text1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_note_text1, 63 );
lv_obj_set_y( ui_note_text1, 44 );
lv_obj_set_align( ui_note_text1, LV_ALIGN_CENTER );
lv_label_set_text(ui_note_text1,"> On the next screen\n\nyou would be ask to\n\ncreate a password.\n\nkindly write down, or\n\nremember this password,\n\nas it is the main\n\ndecryption key for \n\nsigning tx. ");
lv_obj_set_style_text_align(ui_note_text1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_note_text1, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_note_text1, 180, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lets_go_button1 = lv_imagebutton_create(ui_note_for_password_creation);
lv_imagebutton_set_src(ui_lets_go_button1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_letsgobutton_png, NULL);
lv_obj_set_width( ui_lets_go_button1, 105);
lv_obj_set_height( ui_lets_go_button1, 50);
lv_obj_set_x( ui_lets_go_button1, -3 );
lv_obj_set_y( ui_lets_go_button1, 168 );
lv_obj_set_align( ui_lets_go_button1, LV_ALIGN_CENTER );

}

void ui_note_for_password_creation_screen_destroy(void)
{
   if (ui_note_for_password_creation) lv_obj_del(ui_note_for_password_creation);

// NULL screen variables
ui_note_for_password_creation= NULL;
ui_time7= NULL;
ui_wifi_enable7= NULL;
ui_wifi_not_enable7= NULL;
ui_Note1= NULL;
ui_note_text1= NULL;
ui_lets_go_button1= NULL;

}
