// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef UI_PASSWORD_FOR_ENCRIPTION_H
#define UI_PASSWORD_FOR_ENCRIPTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_password_for_encription
extern void ui_password_for_encription_screen_init(void);
extern void ui_password_for_encription_screen_destroy(void);
extern lv_obj_t *ui_password_for_encription;
extern lv_obj_t *ui_input_password_label1;
extern void ui_event_password_box1( lv_event_t * e);
extern lv_obj_t *ui_password_box1;
extern lv_obj_t *ui_Keyboard2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

