// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_password_for_encription = NULL;lv_obj_t *ui_input_password_label1 = NULL;lv_obj_t *ui_password_box1 = NULL;lv_obj_t *ui_Keyboard2 = NULL;
// event funtions
void ui_event_password_box1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard2,  ui_password_box1);
}
}

// build funtions

void ui_password_for_encription_screen_init(void)
{
ui_password_for_encription = lv_obj_create(NULL);
lv_obj_remove_flag( ui_password_for_encription, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_password_for_encription, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_password_for_encription, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_input_password_label1 = lv_label_create(ui_password_for_encription);
lv_obj_set_width( ui_input_password_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_input_password_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_input_password_label1, -3 );
lv_obj_set_y( ui_input_password_label1, -145 );
lv_obj_set_align( ui_input_password_label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_input_password_label1,"input\npassowrd");
lv_obj_set_style_text_align(ui_input_password_label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_input_password_label1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_input_password_label1, &ui_font_pixel_heading, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_password_box1 = lv_textarea_create(ui_password_for_encription);
lv_obj_set_width( ui_password_box1, 212);
lv_obj_set_height( ui_password_box1, 70);
lv_obj_set_x( ui_password_box1, 1 );
lv_obj_set_y( ui_password_box1, -46 );
lv_obj_set_align( ui_password_box1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_password_box1,"Placeholder...");
lv_obj_set_style_border_color(ui_password_box1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_password_box1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard2 = lv_keyboard_create(ui_password_for_encription);
lv_obj_set_width( ui_Keyboard2, 321);
lv_obj_set_height( ui_Keyboard2, 194);
lv_obj_set_x( ui_Keyboard2, 0 );
lv_obj_set_y( ui_Keyboard2, 143 );
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0x8BBE6A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_password_box1, ui_event_password_box1, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard2,ui_password_box1);

}

void ui_password_for_encription_screen_destroy(void)
{
   if (ui_password_for_encription) lv_obj_del(ui_password_for_encription);

// NULL screen variables
ui_password_for_encription= NULL;
ui_input_password_label1= NULL;
ui_password_box1= NULL;
ui_Keyboard2= NULL;

}
