// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef UI_SETTING_SCREEN_H
#define UI_SETTING_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_setting_screen
extern void ui_setting_screen_screen_init(void);
extern void ui_setting_screen_screen_destroy(void);
extern lv_obj_t *ui_setting_screen;
extern lv_obj_t *ui_wifi;
extern lv_obj_t *ui_Switch1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

