// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_event_Screen3( lv_event_t * e);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_time3;
extern lv_obj_t *ui_wifi_not_enable3;
extern lv_obj_t *ui_wifi_enable3;
extern lv_obj_t *ui_whichscreenmark3;
extern lv_obj_t *ui_bottom_image_for_page2;
extern lv_obj_t *ui_ImgButton3;
extern lv_obj_t *ui_arrow4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

