// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_time = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_aoprice = NULL;lv_obj_t *ui_arprice = NULL;lv_obj_t *ui_personname = NULL;lv_obj_t *ui_arrow = NULL;lv_obj_t *ui_whichscreenmark = NULL;lv_obj_t *ui_wifi_not_enable = NULL;lv_obj_t *ui_wifi_enable = NULL;
// event funtions
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
}
}

void ui_event_Panel1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_aoprice, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
      _ui_flag_modify( ui_arprice, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time, -56 );
lv_obj_set_y( ui_time, -216 );
lv_obj_set_align( ui_time, LV_ALIGN_CENTER );
lv_label_set_text(ui_time,"12:30PM");
lv_obj_set_style_text_font(ui_time, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_time, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Image1, &ui_img_profile2_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 0 );
lv_obj_set_y( ui_Image1, -31 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image1,200);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 100);
lv_obj_set_height( ui_Panel1, 50);
lv_obj_set_x( ui_Panel1, 8 );
lv_obj_set_y( ui_Panel1, 207 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_aoprice = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_aoprice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aoprice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_aoprice, -1 );
lv_obj_set_y( ui_aoprice, 1 );
lv_obj_set_align( ui_aoprice, LV_ALIGN_CENTER );
lv_label_set_text(ui_aoprice,"AO$15.09");
lv_obj_add_flag( ui_aoprice, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_arprice = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_arprice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_arprice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_arprice, 2 );
lv_obj_set_y( ui_arprice, 1 );
lv_obj_set_align( ui_arprice, LV_ALIGN_CENTER );
lv_label_set_text(ui_arprice,"AR$13.09");

ui_personname = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_personname, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_personname, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_personname, 7 );
lv_obj_set_y( ui_personname, 92 );
lv_obj_set_align( ui_personname, LV_ALIGN_CENTER );
lv_label_set_text(ui_personname,"Hope's\nVault");
lv_obj_set_style_text_align(ui_personname, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_personname, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arrow = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_arrow, 133 );
lv_obj_set_y( ui_arrow, -23 );
lv_obj_set_align( ui_arrow, LV_ALIGN_CENTER );
lv_label_set_text(ui_arrow,">");
lv_obj_set_style_text_align(ui_arrow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_arrow, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_arrow, 450, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_whichscreenmark = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_whichscreenmark, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_whichscreenmark, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_whichscreenmark, -19 );
lv_obj_set_y( ui_whichscreenmark, 136 );
lv_obj_set_align( ui_whichscreenmark, LV_ALIGN_CENTER );
lv_label_set_text(ui_whichscreenmark,"_ . .");
lv_obj_set_style_text_align(ui_whichscreenmark, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_whichscreenmark, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_whichscreenmark, 450, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_not_enable = lv_image_create(ui_Screen1);
lv_image_set_src(ui_wifi_not_enable, &ui_img_wifi_not_enable_png);
lv_obj_set_width( ui_wifi_not_enable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_not_enable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_not_enable, 113 );
lv_obj_set_y( ui_wifi_not_enable, -213 );
lv_obj_set_align( ui_wifi_not_enable, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_not_enable, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_not_enable, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_not_enable,100);

ui_wifi_enable = lv_image_create(ui_Screen1);
lv_image_set_src(ui_wifi_enable, &ui_img_wifi_enable_png);
lv_obj_set_width( ui_wifi_enable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_enable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_enable, 113 );
lv_obj_set_y( ui_wifi_enable, -213 );
lv_obj_set_align( ui_wifi_enable, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_enable, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_enable, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_enable,100);

lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_time= NULL;
ui_Image1= NULL;
ui_Panel1= NULL;
ui_aoprice= NULL;
ui_arprice= NULL;
ui_personname= NULL;
ui_arrow= NULL;
ui_whichscreenmark= NULL;
ui_wifi_not_enable= NULL;
ui_wifi_enable= NULL;

}
