// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_whichscreenmark2 = NULL;lv_obj_t *ui_settingbutton = NULL;
// event funtions
void ui_event_Screen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
}
}

void ui_event_settingbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_setting_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_setting_screen_screen_init);
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_whichscreenmark2 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_whichscreenmark2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_whichscreenmark2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_whichscreenmark2, -19 );
lv_obj_set_y( ui_whichscreenmark2, 136 );
lv_obj_set_align( ui_whichscreenmark2, LV_ALIGN_CENTER );
lv_label_set_text(ui_whichscreenmark2,". _ .");
lv_obj_set_style_text_align(ui_whichscreenmark2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_whichscreenmark2, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_whichscreenmark2, 450, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settingbutton = lv_imagebutton_create(ui_Screen2);
lv_imagebutton_set_src(ui_settingbutton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_settingsicon_png, NULL);
lv_obj_set_width( ui_settingbutton, 238);
lv_obj_set_height( ui_settingbutton, 120);
lv_obj_set_x( ui_settingbutton, 6 );
lv_obj_set_y( ui_settingbutton, -11 );
lv_obj_set_align( ui_settingbutton, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_settingbutton, ui_event_settingbutton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_whichscreenmark2= NULL;
ui_settingbutton= NULL;

}
