// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef UI_WORD_COUNT_H
#define UI_WORD_COUNT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_word_count
extern void ui_word_count_screen_init(void);
extern void ui_word_count_screen_destroy(void);
extern lv_obj_t *ui_word_count;
extern lv_obj_t *ui_time6;
extern lv_obj_t *ui_wifi_enable6;
extern lv_obj_t *ui_wifi_not_enable6;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_word;
extern lv_obj_t *ui_back_button1;
extern lv_obj_t *ui_next_button;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

