// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef UI_WORDS_SCREEN_H
#define UI_WORDS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_words_screen
extern void ui_words_screen_screen_init(void);
extern void ui_words_screen_screen_destroy(void);
extern lv_obj_t *ui_words_screen;
extern lv_obj_t *ui_time6;
extern lv_obj_t *ui_wifi_not_enable6;
extern lv_obj_t *ui_wifi_enable6;
extern lv_obj_t *ui_number_count_for_words;
extern lv_obj_t *ui_words;
extern lv_obj_t *ui_ImgButton5;
extern lv_obj_t *ui_ImgButton6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

