// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef UI_WALLET_GENERATION_WAITING_SCREEN_H
#define UI_WALLET_GENERATION_WAITING_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wallet_generation_waiting_screen
extern void ui_wallet_generation_waiting_screen_screen_init(void);
extern void ui_wallet_generation_waiting_screen_screen_destroy(void);
extern lv_obj_t *ui_wallet_generation_waiting_screen;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_time4;
extern lv_obj_t *ui_wifi_enable4;
extern lv_obj_t *ui_wifi_not_enable4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

