// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_wallet_generation_waiting_screen = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_time4 = NULL;lv_obj_t *ui_wifi_enable4 = NULL;lv_obj_t *ui_wifi_not_enable4 = NULL;
// event funtions

// build funtions

void ui_wallet_generation_waiting_screen_screen_init(void)
{
ui_wallet_generation_waiting_screen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_wallet_generation_waiting_screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wallet_generation_waiting_screen, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wallet_generation_waiting_screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image6 = lv_image_create(ui_wallet_generation_waiting_screen);
lv_image_set_src(ui_Image6, &ui_img_wallet_watiting_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image6, 6 );
lv_obj_set_y( ui_Image6, 11 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image6,200);

ui_time4 = lv_label_create(ui_wallet_generation_waiting_screen);
lv_obj_set_width( ui_time4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time4, -34 );
lv_obj_set_y( ui_time4, -216 );
lv_obj_set_align( ui_time4, LV_ALIGN_CENTER );
lv_label_set_text(ui_time4,"12:30PM");
lv_obj_set_style_text_font(ui_time4, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_time4, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_enable4 = lv_image_create(ui_wallet_generation_waiting_screen);
lv_image_set_src(ui_wifi_enable4, &ui_img_wifi_enable_png);
lv_obj_set_width( ui_wifi_enable4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_enable4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_enable4, 113 );
lv_obj_set_y( ui_wifi_enable4, -213 );
lv_obj_set_align( ui_wifi_enable4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_enable4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_enable4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_enable4,100);

ui_wifi_not_enable4 = lv_image_create(ui_wallet_generation_waiting_screen);
lv_image_set_src(ui_wifi_not_enable4, &ui_img_wifi_not_enable_png);
lv_obj_set_width( ui_wifi_not_enable4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_not_enable4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_not_enable4, 113 );
lv_obj_set_y( ui_wifi_not_enable4, -213 );
lv_obj_set_align( ui_wifi_not_enable4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_not_enable4, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_not_enable4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_not_enable4,100);

}

void ui_wallet_generation_waiting_screen_screen_destroy(void)
{
   if (ui_wallet_generation_waiting_screen) lv_obj_del(ui_wallet_generation_waiting_screen);

// NULL screen variables
ui_wallet_generation_waiting_screen= NULL;
ui_Image6= NULL;
ui_time4= NULL;
ui_wifi_enable4= NULL;
ui_wifi_not_enable4= NULL;

}
