// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_word_count = NULL;lv_obj_t *ui_time6 = NULL;lv_obj_t *ui_wifi_enable6 = NULL;lv_obj_t *ui_wifi_not_enable6 = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_word = NULL;lv_obj_t *ui_back_button1 = NULL;lv_obj_t *ui_next_button = NULL;
// event funtions

// build funtions

void ui_word_count_screen_init(void)
{
ui_word_count = lv_obj_create(NULL);
lv_obj_remove_flag( ui_word_count, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_word_count, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_word_count, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time6 = lv_label_create(ui_word_count);
lv_obj_set_width( ui_time6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time6, -34 );
lv_obj_set_y( ui_time6, -216 );
lv_obj_set_align( ui_time6, LV_ALIGN_CENTER );
lv_label_set_text(ui_time6,"12:30PM");
lv_obj_set_style_text_font(ui_time6, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_time6, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_enable6 = lv_image_create(ui_word_count);
lv_image_set_src(ui_wifi_enable6, &ui_img_wifi_enable_png);
lv_obj_set_width( ui_wifi_enable6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_enable6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_enable6, 113 );
lv_obj_set_y( ui_wifi_enable6, -213 );
lv_obj_set_align( ui_wifi_enable6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_enable6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_enable6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_enable6,100);

ui_wifi_not_enable6 = lv_image_create(ui_word_count);
lv_image_set_src(ui_wifi_not_enable6, &ui_img_wifi_not_enable_png);
lv_obj_set_width( ui_wifi_not_enable6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_not_enable6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_not_enable6, 113 );
lv_obj_set_y( ui_wifi_not_enable6, -213 );
lv_obj_set_align( ui_wifi_not_enable6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_not_enable6, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_not_enable6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_not_enable6,100);

ui_Label12 = lv_label_create(ui_word_count);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -7 );
lv_obj_set_y( ui_Label12, -99 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"12/01");
lv_obj_set_style_text_font(ui_Label12, &ui_font_pixel_heading, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_word = lv_label_create(ui_word_count);
lv_obj_set_width( ui_word, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_word, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_word, 0 );
lv_obj_set_y( ui_word, -27 );
lv_obj_set_align( ui_word, LV_ALIGN_CENTER );
lv_label_set_text(ui_word,"doctor");
lv_obj_set_style_text_decor(ui_word, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_word, &ui_font_pixel_heading, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_back_button1 = lv_imagebutton_create(ui_word_count);
lv_imagebutton_set_src(ui_back_button1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backbutton_png, NULL);
lv_obj_set_width( ui_back_button1, 147);
lv_obj_set_height( ui_back_button1, 71);
lv_obj_set_x( ui_back_button1, -74 );
lv_obj_set_y( ui_back_button1, 85 );
lv_obj_set_align( ui_back_button1, LV_ALIGN_CENTER );

ui_next_button = lv_imagebutton_create(ui_word_count);
lv_imagebutton_set_src(ui_next_button, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_nextbutton_png, NULL);
lv_obj_set_width( ui_next_button, 147);
lv_obj_set_height( ui_next_button, 69);
lv_obj_set_x( ui_next_button, 77 );
lv_obj_set_y( ui_next_button, 85 );
lv_obj_set_align( ui_next_button, LV_ALIGN_CENTER );

}

void ui_word_count_screen_destroy(void)
{
   if (ui_word_count) lv_obj_del(ui_word_count);

// NULL screen variables
ui_word_count= NULL;
ui_time6= NULL;
ui_wifi_enable6= NULL;
ui_wifi_not_enable6= NULL;
ui_Label12= NULL;
ui_word= NULL;
ui_back_button1= NULL;
ui_next_button= NULL;

}
