// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_wifi_password_screen = NULL;lv_obj_t *ui_input_password_label = NULL;lv_obj_t *ui_password_box = NULL;lv_obj_t *ui_wifi_device_name = NULL;lv_obj_t *ui_Keyboard1 = NULL;
// event funtions
void ui_event_password_box( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_password_box);
}
}

// build funtions

void ui_wifi_password_screen_screen_init(void)
{
ui_wifi_password_screen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_wifi_password_screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wifi_password_screen, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifi_password_screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_input_password_label = lv_label_create(ui_wifi_password_screen);
lv_obj_set_width( ui_input_password_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_input_password_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_input_password_label, -27 );
lv_obj_set_y( ui_input_password_label, -192 );
lv_obj_set_align( ui_input_password_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_input_password_label,"input\npassowrd");
lv_obj_set_style_text_align(ui_input_password_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_input_password_label, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_input_password_label, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_input_password_label, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_password_box = lv_textarea_create(ui_wifi_password_screen);
lv_obj_set_width( ui_password_box, 212);
lv_obj_set_height( ui_password_box, 70);
lv_obj_set_x( ui_password_box, 1 );
lv_obj_set_y( ui_password_box, -46 );
lv_obj_set_align( ui_password_box, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_password_box,"Placeholder...");
lv_obj_set_style_border_color(ui_password_box, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_password_box, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_device_name = lv_label_create(ui_wifi_password_screen);
lv_obj_set_width( ui_wifi_device_name, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_device_name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_device_name, -9 );
lv_obj_set_y( ui_wifi_device_name, -104 );
lv_obj_set_align( ui_wifi_device_name, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifi_device_name,"jio4g");
lv_obj_set_style_text_align(ui_wifi_device_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifi_device_name, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_wifi_device_name, 250, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard1 = lv_keyboard_create(ui_wifi_password_screen);
lv_obj_set_width( ui_Keyboard1, 321);
lv_obj_set_height( ui_Keyboard1, 194);
lv_obj_set_x( ui_Keyboard1, 0 );
lv_obj_set_y( ui_Keyboard1, 143 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x8BBE6A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_password_box, ui_event_password_box, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard1,ui_password_box);

}

void ui_wifi_password_screen_screen_destroy(void)
{
   if (ui_wifi_password_screen) lv_obj_del(ui_wifi_password_screen);

// NULL screen variables
ui_wifi_password_screen= NULL;
ui_input_password_label= NULL;
ui_password_box= NULL;
ui_wifi_device_name= NULL;
ui_Keyboard1= NULL;

}
