// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"

lv_obj_t *ui_words_screen = NULL;lv_obj_t *ui_time6 = NULL;lv_obj_t *ui_wifi_not_enable6 = NULL;lv_obj_t *ui_wifi_enable6 = NULL;lv_obj_t *ui_number_count_for_words = NULL;lv_obj_t *ui_words = NULL;lv_obj_t *ui_ImgButton5 = NULL;lv_obj_t *ui_ImgButton6 = NULL;
// event funtions

// build funtions

void ui_words_screen_screen_init(void)
{
ui_words_screen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_words_screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_words_screen, lv_color_hex(0x88BF6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_words_screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time6 = lv_label_create(ui_words_screen);
lv_obj_set_width( ui_time6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time6, -34 );
lv_obj_set_y( ui_time6, -216 );
lv_obj_set_align( ui_time6, LV_ALIGN_CENTER );
lv_label_set_text(ui_time6,"12:30PM");
lv_obj_set_style_text_font(ui_time6, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_time6, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_not_enable6 = lv_image_create(ui_words_screen);
lv_image_set_src(ui_wifi_not_enable6, &ui_img_wifi_not_enable_png);
lv_obj_set_width( ui_wifi_not_enable6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_not_enable6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_not_enable6, 113 );
lv_obj_set_y( ui_wifi_not_enable6, -213 );
lv_obj_set_align( ui_wifi_not_enable6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_not_enable6, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_not_enable6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_not_enable6,100);

ui_wifi_enable6 = lv_image_create(ui_words_screen);
lv_image_set_src(ui_wifi_enable6, &ui_img_wifi_enable_png);
lv_obj_set_width( ui_wifi_enable6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_enable6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_enable6, 113 );
lv_obj_set_y( ui_wifi_enable6, -213 );
lv_obj_set_align( ui_wifi_enable6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_enable6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wifi_enable6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_wifi_enable6,100);

ui_number_count_for_words = lv_label_create(ui_words_screen);
lv_obj_set_width( ui_number_count_for_words, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_number_count_for_words, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_number_count_for_words, -16 );
lv_obj_set_y( ui_number_count_for_words, -85 );
lv_obj_set_align( ui_number_count_for_words, LV_ALIGN_CENTER );
lv_label_set_text(ui_number_count_for_words,"12/01");
lv_obj_set_style_text_font(ui_number_count_for_words, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_number_count_for_words, 350, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_words = lv_label_create(ui_words_screen);
lv_obj_set_width( ui_words, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_words, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_words, -26 );
lv_obj_set_y( ui_words, -39 );
lv_obj_set_align( ui_words, LV_ALIGN_CENTER );
lv_label_set_text(ui_words,"doctor");
lv_obj_set_style_text_decor(ui_words, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_words, &ui_font_Pixel, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_words, 400, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton5 = lv_imagebutton_create(ui_words_screen);
lv_imagebutton_set_src(ui_ImgButton5, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backbutton_png, NULL);
lv_obj_set_width( ui_ImgButton5, 145);
lv_obj_set_height( ui_ImgButton5, 73);
lv_obj_set_x( ui_ImgButton5, -77 );
lv_obj_set_y( ui_ImgButton5, 84 );
lv_obj_set_align( ui_ImgButton5, LV_ALIGN_CENTER );

ui_ImgButton6 = lv_imagebutton_create(ui_words_screen);
lv_imagebutton_set_src(ui_ImgButton6, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_nextbutton_png, NULL);
lv_obj_set_width( ui_ImgButton6, 143);
lv_obj_set_height( ui_ImgButton6, 71);
lv_obj_set_x( ui_ImgButton6, 81 );
lv_obj_set_y( ui_ImgButton6, 81 );
lv_obj_set_align( ui_ImgButton6, LV_ALIGN_CENTER );

}

void ui_words_screen_screen_destroy(void)
{
   if (ui_words_screen) lv_obj_del(ui_words_screen);

// NULL screen variables
ui_words_screen= NULL;
ui_time6= NULL;
ui_wifi_not_enable6= NULL;
ui_wifi_enable6= NULL;
ui_number_count_for_words= NULL;
ui_words= NULL;
ui_ImgButton5= NULL;
ui_ImgButton6= NULL;

}
