// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
	lv_display_t *dispp = lv_display_get_default();
	lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
	lv_display_set_theme(dispp, theme);
	ui_Screen1_screen_init();
	ui_Screen2_screen_init();
	ui_Screen3_screen_init();
	ui_setting_screen_screen_init();
	ui_note_for_words_screen_screen_init();
	ui_new_note_for_word_count_screen_init();
	ui_word_count_screen_init();
	ui_last_word_count_screen_init();
	/* note_for_password, password_for_encryption, wallet_generation_waiting_screen created on demand to avoid LVGL task watchdog when tapping Wallet */
	ui____initial_actions0 = NULL;
	lv_scr_load(ui_Screen1);
}

void ui_destroy( void )
{
	ui_Screen1_screen_destroy();
	ui_Screen2_screen_destroy();
	ui_Screen3_screen_destroy();
	ui_setting_screen_screen_destroy();
	ui_wallet_generation_waiting_screen_screen_destroy();
	ui_wallet_exists_screen_screen_destroy();
	ui_note_for_words_screen_screen_destroy();
	ui_new_note_for_word_count_screen_destroy();
	ui_word_count_screen_destroy();
	ui_last_word_count_screen_destroy();
	/* destroy on-demand screens if they were ever created */
	ui_note_for_password_screen_destroy();
	ui_password_for_encryption_screen_destroy();
	ui_wifi_password_screen_screen_destroy();
}
