// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
	lv_display_t *dispp = lv_display_get_default();
	lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
	lv_display_set_theme(dispp, theme);
	ui_Screen1_screen_init();
	ui_Screen2_screen_init();
	ui_setting_screen_screen_init();
	/* Do not create extra screen - can paint white on top on some ports */
	ui____initial_actions0 = NULL;
	lv_scr_load(ui_Screen1);
}

void ui_destroy( void )
{
	ui_Screen1_screen_destroy();
	ui_Screen2_screen_destroy();
	ui_setting_screen_screen_destroy();
	ui_wifi_password_screen_screen_destroy();
}
