// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef _WALLET3_UI_H
#define _WALLET3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_setting_screen.h"
#include "screens/ui_wallet_no_wallet_screen.h"
#include "screens/ui_wallet_generation_waiting_screen.h"
#include "screens/ui_public_address_qr_screen.h"
#include "screens/ui_wallet_exists_screen.h"
#include "screens/ui_note_for_words_screen.h"
#include "screens/ui_new_note_for_word_count.h"
#include "screens/ui_word_count.h"
#include "screens/ui_last_word_count.h"
#include "screens/ui_generating_public_address.h"
#include "screens/ui_note_for_password.h"
#include "screens/ui_password_for_encryption.h"
#include "screens/ui_wifi_password_screen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_profile2_png);   // assets/profile2.png
LV_IMG_DECLARE( ui_img_settingsicon_png);   // assets/settingsicon.png
LV_IMG_DECLARE( ui_img_wifi_not_enable_png);
LV_IMG_DECLARE( ui_img_wifi_enable_png);
LV_IMG_DECLARE( ui_img_wallet_png);
LV_IMG_DECLARE( ui_img_wallet_watiting_png);
LV_IMG_DECLARE( ui_img_under_image_png);
LV_IMG_DECLARE( ui_img_verification_png);
LV_IMG_DECLARE( ui_img_letsgobutton_png);
LV_IMG_DECLARE( ui_img_backbutton_png);
LV_IMG_DECLARE( ui_img_nextbutton_png);
LV_IMG_DECLARE( ui_img_finishbutton_png);

// FONTS
LV_FONT_DECLARE( ui_font_Pixel);
LV_FONT_DECLARE( ui_font_pixel_heading);
LV_FONT_DECLARE( ui_font_pixel_wordings_small);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
