// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: wallet3

#ifndef _WALLET3_UI_H
#define _WALLET3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_setting_screen.h"
#include "screens/ui_wallet_gen_screen.h"
#include "screens/ui_wifi_password_screen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_profile2_png);   // assets/profile2.png
LV_IMG_DECLARE( ui_img_settingsicon_png);   // assets/settingsicon.png
LV_IMG_DECLARE( ui_img_wifi_not_enable_png);
LV_IMG_DECLARE( ui_img_wifi_enable_png);
LV_IMG_DECLARE( ui_img_wallet_png);
LV_IMG_DECLARE( ui_img_under_image_png);
LV_IMG_DECLARE( ui_img_verification_png);

// FONTS
LV_FONT_DECLARE( ui_font_Pixel);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
