// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: hardware_wallet_01

#include "ui_events.h"

void (*app_screen2_init_cb)(lv_obj_t *screen2) = NULL;
